export const UserLabels = {
    headerTitle: 'User Management',
    firstName : 'First Name',
    middleName: 'Middle Name',
    lastName : 'Last Name',
    email : 'Email',
    actionHeader: 'Actions',
    editIconTitle: 'Edit User details',
    deleteIconTitle: 'Delete User',
    firstNamePlaceHolder: 'Enter First Name',
    middleNamePlaceHolder: 'Enter Middle Name',
    lastNamePlaceHolder: 'Enter Last Name',
    emailPlaceHolder: 'Enter Email',
    userListHeader: 'User List',
    addNewUserHeader: 'Add New User',
    updateUserHeader: 'Update User details',
    addUserBtn: 'Add User',
    updateUserBtn: 'Update User',
    backBtn: 'Back',
    noUserRecords: 'No User recors found. Please add users by clicking on the below button',
    ModalTitle: 'Do you want to delete the user record?',
    continueBtnTitle: 'Confirm',
    cancelBtnTitle: 'Cancel'
}
